// api
export const API_REQUEST 	 = '[ API ] API_REQUEST';
export const REQUEST_SUCCESS = '[ API ] REQUEST_SUCCESS';
export const REQUEST_FAILED  = '[ API ] REQUEST_FAILED';

// serverside table
export const GET_TABLE_DATA = '[ UI SERVERSIDE_TABLE ] SAVE_TABLE';
export const BUILD_TABLE    = '[ UI SERVERSIDE_TABLE ] BUILD_TABLE';
export const DESTROY_TABLE  = '[ UI SERVERSIDE_TABLE ] DESTROY_TABLE';

// form
export const GET_CURRENT_FORM = '[ UI FORM ] GET_CURRENT_FORM';
export const REMOVE_FORM 	  = '[ UI FORM ] REMOVE_FORM';

// ui
// fetch
export const SHOW_FETCH_LOADER = '[ UI ] SHOW_FETCH_LOADER';
export const HIDE_FETCH_LOADER = '[ UI ] HIDE_FETCH_LOADER';
// post
export const SHOW_POST_LOADER  = '[ UI ] SHOW_POST_LOADER';
export const HIDE_POST_LOADER  = '[ UI ] HIDE_POST_LOADER';

// todos
export const CLEAR_CLASS_TODOS  = '[TODOS] CLEAR_CLASS_TODOS';
// userid
export const HAS_ERROR_USERID 	= '[TODOS] HAS_ERROR_USERID';
export const HAS_SUCCESS_USERID = '[TODOS] HAS_SUCCESS_USERID';
export const IS_VALID_USERID 	= '[TODOS] IS_VALID_USERID';
export const SET_ERROR_USERID 	= '[TODOS] SET_ERROR_USERID';
export const CLEAR_USERID 		= '[TODOS] CLEAR_USERID'
// title
export const HAS_ERROR_TITLE    = '[TODOS] HAS_ERROR_TITLE';
export const HAS_SUCCESS_TITLE  = '[TODOS] HAS_SUCCESS_TITLE';
export const IS_VALID_TITLE 	= '[TODOS] IS_VALID_TITLE';
export const SET_ERROR_TITLE 	= '[TODOS] SET_ERROR_TITLE';
export const CLEAR_TITLE 		= '[TODOS] CLEAR_TITLE'

// users
export const CLEAR_USERS = '[USERS] CLEAR_USERS';
// first name
export const HAS_ERROR_FIRSTNAME   = '[USERS] HAS_ERROR_FIRSTNAME';
export const HAS_SUCCESS_FIRSTNAME = '[USERS] HAS_SUCCESS_FIRSTNAME';
export const SET_ERROR_FIRSTNAME   = '[USERS] SET_ERROR_FIRSTNAME';
export const CLEAR_FIRSTNAME 	   = '[USERS] CLEAR_FIRSTNAME';

// middle name
export const HAS_ERROR_MIDDLENAME 	= '[USERS] HAS_ERROR_MIDDLENAME';
export const HAS_SUCCESS_MIDDLENAME = '[USERS] HAS_SUCCESS_MIDDLENAME';
export const SET_ERROR_MIDDLENAME   = '[USERS] SET_ERROR_MIDDLENAME';
export const CLEAR_MIDDLENAME 	   	= '[USERS] CLEAR_MIDDLENAME';

// last name
export const HAS_ERROR_LASTNAME   = '[USERS] HAS_ERROR_LASTNAME';
export const HAS_SUCCESS_LASTNAME = '[USERS] HAS_SUCCESS_LASTNAME';
export const SET_ERROR_LASTNAME   = '[USERS] SET_ERROR_LASTNAME';
export const CLEAR_LASTNAME 	  = '[USERS] CLEAR_LASTNAME';

// username
export const HAS_ERROR_USERNAME   = '[USERS] HAS_ERROR_USERNAME';
export const HAS_SUCCESS_USERNAME = '[USERS] HAS_SUCCESS_USERNAME';
export const SET_ERROR_USERNAME   = '[USERS] SET_ERROR_USERNAME';
export const CLEAR_USERNAME 	  = '[USERS] CLEAR_USERNAME';

// password
export const HAS_ERROR_PASSWORD   = '[USERS] HAS_ERROR_PASSWORD';
export const HAS_SUCCESS_PASSWORD = '[USERS] HAS_SUCCESS_PASSWORD';
export const SET_ERROR_PASSWORD   = '[USERS] SET_ERROR_PASSWORD';
export const CLEAR_PASSWORD 	  = '[USERS] CLEAR_PASSWORD';

// status
export const HAS_ERROR_STATUS   = '[USERS] HAS_ERROR_STATUS';
export const HAS_SUCCESS_STATUS = '[USERS] HAS_SUCCESS_STATUS';
export const SET_ERROR_STATUS   = '[USERS] SET_ERROR_STATUS';
export const CLEAR_STATUS 	  	= '[USERS] CLEAR_STATUS';

// role
export const HAS_ERROR_ROLE   = '[USERS] HAS_ERROR_ROLE';
export const HAS_SUCCESS_ROLE = '[USERS] HAS_SUCCESS_ROLE';
export const SET_ERROR_ROLE   = '[USERS] SET_ERROR_ROLE';
export const CLEAR_ROLE 	  = '[USERS] CLEAR_ROLE';

export const VALID_USERNAME 	= '[ UI LOGIN ] VALID_USERNAME';
export const INVALID_USERNAME 	= '[ UI LOGIN ] INVALID_USERNAME';

export const VALID_PASSWORD 	= '[ UI LOGIN ] VALID_PASSWORD';
export const INVALID_PASSWORD 	= '[ UI LOGIN ] INVALID_PASSWORD';

export const RECEIVE_USERDATA = '[ USER ] RECEIVE_USERDATA';
export const AUTHENTICATE = '[ USER ] AUTHENTICATE';

export const REMOVE_USERDATA = '[ USER ] REMOVE_USERDATA';
export const DEAUTHENTICATE = '[ USER ] DEAUTHENTICATE';