// COUNTER_
export const INCREMENT  = 'INCREMENT';
export const DECREMENT	= 'DECREMENT';

// USERS_
// FETCH
export const FETCH_USERS_BEGIN   = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// HANDLE
export const HANDLE_FIRSTNAME 	= 'HANDLE_FIRSTNAME';
export const HANDLE_MIDDLENAME 	= 'HANDLE_MIDDLENAME';
export const HANDLE_LASTNAME 	= 'HANDLE_LASTNAME';
export const HANDLE_USERNAME 	= 'HANDLE_USERNAME';

// ADD
export const ADD_USER = 'ADD_USER';

// TODO_
export const ADD_TODO = 'ADD_TODO';