// COUNTER_
export const INCREMENT  = 'INCREMENT';
export const DECREMENT	= 'DECREMENT';

// USERS_
// FETCH
export const FETCH_USERS_BEGIN   = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// HANDLE
export const HANDLE_FIRSTNAME 	= 'HANDLE_FIRSTNAME';
export const HANDLE_MIDDLENAME 	= 'HANDLE_MIDDLENAME';
export const HANDLE_LASTNAME 	= 'HANDLE_LASTNAME';
export const HANDLE_USERNAME 	= 'HANDLE_USERNAME';

// CREATE
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_BEGIN = 'CREATE_USER_BEGIN';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const CLEAR_FIELDS = 'CLEAR_FIELDS';

// TODO_
export const ADD_TODO = 'ADD_TODO';